AllCops:
  TargetRubyVersion: 2.7

Metrics:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/WhenThen:
  Enabled: false
