AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Metrics:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/WhenThen:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Layout/LineLength:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false
